// build.rs
use std::{
    env, fs,
    path::{Path, PathBuf},
};

fn main() -> anyhow::Result<()> {
    let pc_names = &["backfill"]; // pkg-config name(s) 
    let lib_basename = "backfill"; // lib file like libfoo.a
    let header_hints = &["backfill/api.h"]; // likely headers to test that an include dir works

    // 1) Try pkg-config first
    if let Some(meta) = try_pkg_config(pc_names) {
        emit_link_info(&meta.lib_paths, &meta.libs);
        let include_dir = meta.include_paths.first().cloned();
        generate_bindings(include_dir.as_deref(), header_hints)?;
        return Ok(());
    }

    // 2) Fall back to env-provided dirs
    let env_inc = env::var_os("BACKFILL_INCLUDE_DIR").map(PathBuf::from);
    let env_lib = env::var_os("BACKFILL_LIB_DIR").map(PathBuf::from);
    let env_prefix = env::var_os("BACKFILL_DIR").map(PathBuf::from);

    // 3) Build candidate prefixes to scan
    let mut prefixes: Vec<PathBuf> = vec![
        PathBuf::from("/usr/local"),
        PathBuf::from("/usr"),
        PathBuf::from("/opt"),
        PathBuf::from("/opt/local"),
    ];
    if let Some(h) = dirs::home_dir() {
        prefixes.insert(0, h.join(".local"));
    }
    if let Some(p) = &env_prefix {
        prefixes.insert(0, p.clone());
    }

    // 4) Resolve include/lib dirs
    let include_dir = env_inc.or_else(|| find_include_dir(&prefixes, header_hints));
    let lib_dir = env_lib.or_else(|| find_lib_dir(&prefixes, lib_basename));

    if include_dir.is_none() || lib_dir.is_none() {
        anyhow::bail!(
            "Could not find headers or library for `{}`.\n\
             Tried pkg-config {:?} and common prefixes {:?}.\n\
             You can set BACKFILL_DIR, BACKFILL_INCLUDE_DIR, and BACKFILL_LIB_DIR to override.",
            lib_basename,
            pc_names,
            prefixes
        );
    }

    let include_dir = include_dir.unwrap();
    let lib_dir = lib_dir.unwrap();

    // 5) Emit link directives
    println!("cargo:rustc-link-search=native={}", lib_dir.display());
    println!("cargo:rustc-link-lib=dylib={}", lib_basename);

    #[cfg(target_os = "macos")]
    {
        // rpaths so the binary can find the dylib at runtime
        for rp in [
            "@loader_path",
            "@executable_path/../Frameworks",
            "@loader_path/../Frameworks",
        ] {
            println!("cargo:rustc-link-arg=-Wl,-rpath,{}", rp);
        }

        println!("cargo:rustc-link-arg=-Wl,-rpath,{}", lib_dir.display());
    }

    #[cfg(target_os = "linux")]
    {
        for rp in ["$ORIGIN", "$ORIGIN/../lib", "$ORIGIN/lib"] {
            println!("cargo:rustc-link-arg=-Wl,-rpath,{}", rp);
        }
    }

    // 6) Generate bindings from the wrapper we create (or skip with feature)
    generate_bindings(Some(&include_dir), header_hints)?;

    Ok(())
}

struct PkgMeta {
    include_paths: Vec<PathBuf>,
    lib_paths: Vec<PathBuf>,
    libs: Vec<String>,
}

fn try_pkg_config(names: &[&str]) -> Option<PkgMeta> {
    for name in names {
        let cfg = pkg_config::Config::new();
        //cfg.statik(true);
        if let Ok(lib) = cfg.probe(name) {
            return Some(PkgMeta {
                include_paths: lib.include_paths,
                lib_paths: lib.link_paths,
                libs: lib.libs,
            });
        }
    }
    None
}

fn emit_link_info(lib_paths: &[PathBuf], libs: &[String]) {
    for p in lib_paths {
        println!("cargo:rustc-link-search=native={}", p.display());
    }
    for l in libs {
        println!("cargo:rustc-link-lib=dylib={}", l);
    }
}

fn find_include_dir(prefixes: &[PathBuf], header_hints: &[&str]) -> Option<PathBuf> {
    for prefix in prefixes {
        for inc in ["include", "include/backfill"].iter() {
            let dir = prefix.join(inc);
            if header_hints.iter().any(|h| dir.join(h).exists()) {
                return Some(dir);
            }
        }
    }
    None
}

fn find_lib_dir(prefixes: &[PathBuf], lib_basename: &str) -> Option<PathBuf> {
    for prefix in prefixes {
        for libdir in ["lib", "lib64"].iter() {
            let dir = prefix.join(libdir);
            let b_lib = dir.join(format!("lib{}.dylib", lib_basename));
            if b_lib.exists() {
                return Some(dir);
            }
            let b_lib = dir.join(format!("lib{}.so", lib_basename));
            if b_lib.exists() {
                return Some(dir);
            }
        }
    }
    None
}

fn generate_bindings(include_dir: Option<&Path>, header_hints: &[&str]) -> anyhow::Result<()> {
    let out_dir = PathBuf::from(env::var("OUT_DIR")?);

    // 1) Create a minimal wrapper header that just includes the library’s public header.
    //    We try the first found header hint relative to include_dir; otherwise we assume it’s
    //    found via the compiler’s include paths (pkg-config case).
    let mut wrapper = String::from("/* Auto-generated by build.rs */\n");
    if let Some(inc) = include_dir {
        if let Some(h) = header_hints
            .iter()
            .map(|h| inc.join(h))
            .find(|p| p.exists())
        {
            // Use a quoted include to pin to the found file
            wrapper.push_str(&format!("#include \"{}\"\n", h.display()));
        } else {
            // Fall back to angle include and let clang search include paths
            wrapper.push_str(&format!("#include <{}>\n", header_hints[0]));
        }
        // Let Rustc/clang know about the include dir
        println!("cargo:include={}", inc.display());
    } else {
        wrapper.push_str(&format!("#include <{}>\n", header_hints[0]));
    }

    let wrapper_h = out_dir.join("wrapper.h");
    fs::write(&wrapper_h, wrapper)?;

    // 2) Configure bindgen
    let mut builder = bindgen::Builder::default()
        .header(wrapper_h.to_string_lossy())
        .layout_tests(false); // makes builds faster/more portable

    if let Some(inc) = include_dir {
        builder = builder.clang_arg(format!("-I{}", inc.display()));
    }

    // Pass target triple if cross-compiling
    if let Ok(target) = env::var("TARGET") {
        builder = builder.clang_arg(format!("--target={}", target));
    }

    let bindings = builder
        .generate()
        .map_err(|_| anyhow::anyhow!("bindgen failed to generate bindings"))?;

    let out_rs = out_dir.join("backfill_bindings.rs");
    bindings.write_to_file(&out_rs)?;

    Ok(())
}
