[package]
name = "tephrite_rs"
version = "0.2.0"
edition = "2024"

[dependencies]
dirs = "6"
bitflags = "2"
bevy = { version = "0.19.0", features = ["jpeg", "exr", "bevy_remote"] }
bytemuck = "1"
itertools = "*"
thiserror = "*"
half = "*"
libc = "0.2"
serde = { version = "*", features = ["derive"] }
toml = "0.9"
cosmic-text = "*"
crossbeam-queue = "*"
bevy_rich_text3d = "0.7"
http = "1.5"
httparse = "1.10"
bytes = "1.12"
anyhow = "*"

# Enable a small amount of optimization in the dev profile.
[profile.dev]
opt-level = 1

# Enable a large amount of optimization in the dev profile for dependencies.
[profile.dev.package."*"]
opt-level = 3

[dev-dependencies]
bevy = { version = "0.19.0", features = [
    "jpeg",
    "exr",
    "bevy_remote",
    "debug",
    "free_camera",
] }
criterion = "0.8"
nix = "0.30"
rand = "*"


[[test]]
name = "shmem_integration"
harness = false

[[test]]
name = "shared_buffer"
harness = false

[[test]]
name = "replication_integration"
harness = false

[[bench]]
name = "asset_serialization"
harness = false

[[bench]]
name = "replication_serialization"
harness = false
