[package]
name = "tephrite_rs"
version = "0.1.0"
edition = "2024"

[build-dependencies]
dirs = "6"
bindgen = "0.72"
pkg-config = "0.3"
anyhow = "1"

[dependencies]
dirs = "6"
bitflags = "2"
bevy = "0.17"
bytemuck = "1"
itertools = "*"
thiserror = "*"
libc = "0.2"
seqlock = "0.2"
serde = { version = "*", features = ["derive"] }
toml = "0.9"

# Enable a small amount of optimization in the dev profile.
[profile.dev]
opt-level = 1

# Enable a large amount of optimization in the dev profile for dependencies.
[profile.dev.package."*"]
opt-level = 3

[dev-dependencies]
nix = "0.30"

[[test]]
name = "shmem_integration"
harness = false

[[test]]
name = "shared_buffer"
harness = false

[[test]]
name = "replication_integration"
harness = false
