/* automatically generated by rust-bindgen 0.72.1 */

pub const __WORDSIZE: u32 = 64;
pub const __has_safe_buffers: u32 = 1;
pub const __DARWIN_ONLY_64_BIT_INO_T: u32 = 1;
pub const __DARWIN_ONLY_UNIX_CONFORMANCE: u32 = 1;
pub const __DARWIN_ONLY_VERS_1050: u32 = 1;
pub const __DARWIN_UNIX03: u32 = 1;
pub const __DARWIN_64_BIT_INO_T: u32 = 1;
pub const __DARWIN_VERS_1050: u32 = 1;
pub const __DARWIN_NON_CANCELABLE: u32 = 0;
pub const __DARWIN_SUF_EXTSN: &[u8; 14] = b"$DARWIN_EXTSN\0";
pub const __DARWIN_C_ANSI: u32 = 4096;
pub const __DARWIN_C_FULL: u32 = 900000;
pub const __DARWIN_C_LEVEL: u32 = 900000;
pub const __STDC_WANT_LIB_EXT1__: u32 = 1;
pub const __DARWIN_NO_LONG_LONG: u32 = 0;
pub const _DARWIN_FEATURE_64_BIT_INODE: u32 = 1;
pub const _DARWIN_FEATURE_ONLY_64_BIT_INODE: u32 = 1;
pub const _DARWIN_FEATURE_ONLY_VERS_1050: u32 = 1;
pub const _DARWIN_FEATURE_ONLY_UNIX_CONFORMANCE: u32 = 1;
pub const _DARWIN_FEATURE_UNIX_CONFORMANCE: u32 = 3;
pub const __has_ptrcheck: u32 = 0;
pub const __has_bounds_safety_attributes: u32 = 0;
pub const USE_CLANG_TYPES: u32 = 0;
pub const __PTHREAD_SIZE__: u32 = 8176;
pub const __PTHREAD_ATTR_SIZE__: u32 = 56;
pub const __PTHREAD_MUTEXATTR_SIZE__: u32 = 8;
pub const __PTHREAD_MUTEX_SIZE__: u32 = 56;
pub const __PTHREAD_CONDATTR_SIZE__: u32 = 8;
pub const __PTHREAD_COND_SIZE__: u32 = 40;
pub const __PTHREAD_ONCE_SIZE__: u32 = 8;
pub const __PTHREAD_RWLOCK_SIZE__: u32 = 192;
pub const __PTHREAD_RWLOCKATTR_SIZE__: u32 = 16;
pub const INT8_MAX: u32 = 127;
pub const INT16_MAX: u32 = 32767;
pub const INT32_MAX: u32 = 2147483647;
pub const INT64_MAX: u64 = 9223372036854775807;
pub const INT8_MIN: i32 = -128;
pub const INT16_MIN: i32 = -32768;
pub const INT32_MIN: i32 = -2147483648;
pub const INT64_MIN: i64 = -9223372036854775808;
pub const UINT8_MAX: u32 = 255;
pub const UINT16_MAX: u32 = 65535;
pub const UINT32_MAX: u32 = 4294967295;
pub const UINT64_MAX: i32 = -1;
pub const INT_LEAST8_MIN: i32 = -128;
pub const INT_LEAST16_MIN: i32 = -32768;
pub const INT_LEAST32_MIN: i32 = -2147483648;
pub const INT_LEAST64_MIN: i64 = -9223372036854775808;
pub const INT_LEAST8_MAX: u32 = 127;
pub const INT_LEAST16_MAX: u32 = 32767;
pub const INT_LEAST32_MAX: u32 = 2147483647;
pub const INT_LEAST64_MAX: u64 = 9223372036854775807;
pub const UINT_LEAST8_MAX: u32 = 255;
pub const UINT_LEAST16_MAX: u32 = 65535;
pub const UINT_LEAST32_MAX: u32 = 4294967295;
pub const UINT_LEAST64_MAX: i32 = -1;
pub const INT_FAST8_MIN: i32 = -128;
pub const INT_FAST16_MIN: i32 = -32768;
pub const INT_FAST32_MIN: i32 = -2147483648;
pub const INT_FAST64_MIN: i64 = -9223372036854775808;
pub const INT_FAST8_MAX: u32 = 127;
pub const INT_FAST16_MAX: u32 = 32767;
pub const INT_FAST32_MAX: u32 = 2147483647;
pub const INT_FAST64_MAX: u64 = 9223372036854775807;
pub const UINT_FAST8_MAX: u32 = 255;
pub const UINT_FAST16_MAX: u32 = 65535;
pub const UINT_FAST32_MAX: u32 = 4294967295;
pub const UINT_FAST64_MAX: i32 = -1;
pub const INTPTR_MAX: u64 = 9223372036854775807;
pub const INTPTR_MIN: i64 = -9223372036854775808;
pub const UINTPTR_MAX: i32 = -1;
pub const SIZE_MAX: i32 = -1;
pub const RSIZE_MAX: i32 = -1;
pub const WINT_MIN: i32 = -2147483648;
pub const WINT_MAX: u32 = 2147483647;
pub const SIG_ATOMIC_MIN: i32 = -2147483648;
pub const SIG_ATOMIC_MAX: u32 = 2147483647;
pub type int_least8_t = i8;
pub type int_least16_t = i16;
pub type int_least32_t = i32;
pub type int_least64_t = i64;
pub type uint_least8_t = u8;
pub type uint_least16_t = u16;
pub type uint_least32_t = u32;
pub type uint_least64_t = u64;
pub type int_fast8_t = i8;
pub type int_fast16_t = i16;
pub type int_fast32_t = i32;
pub type int_fast64_t = i64;
pub type uint_fast8_t = u8;
pub type uint_fast16_t = u16;
pub type uint_fast32_t = u32;
pub type uint_fast64_t = u64;
pub type __int8_t = ::std::os::raw::c_schar;
pub type __uint8_t = ::std::os::raw::c_uchar;
pub type __int16_t = ::std::os::raw::c_short;
pub type __uint16_t = ::std::os::raw::c_ushort;
pub type __int32_t = ::std::os::raw::c_int;
pub type __uint32_t = ::std::os::raw::c_uint;
pub type __int64_t = ::std::os::raw::c_longlong;
pub type __uint64_t = ::std::os::raw::c_ulonglong;
pub type __darwin_intptr_t = ::std::os::raw::c_long;
pub type __darwin_natural_t = ::std::os::raw::c_uint;
pub type __darwin_ct_rune_t = ::std::os::raw::c_int;
#[repr(C)]
#[derive(Copy, Clone)]
pub union __mbstate_t {
    pub __mbstate8: [::std::os::raw::c_char; 128usize],
    pub _mbstateL: ::std::os::raw::c_longlong,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of __mbstate_t"][::std::mem::size_of::<__mbstate_t>() - 128usize];
    ["Alignment of __mbstate_t"][::std::mem::align_of::<__mbstate_t>() - 8usize];
    ["Offset of field: __mbstate_t::__mbstate8"]
        [::std::mem::offset_of!(__mbstate_t, __mbstate8) - 0usize];
    ["Offset of field: __mbstate_t::_mbstateL"]
        [::std::mem::offset_of!(__mbstate_t, _mbstateL) - 0usize];
};
pub type __darwin_mbstate_t = __mbstate_t;
pub type __darwin_ptrdiff_t = ::std::os::raw::c_long;
pub type __darwin_size_t = ::std::os::raw::c_ulong;
pub type __darwin_va_list = __builtin_va_list;
pub type __darwin_wchar_t = ::std::os::raw::c_int;
pub type __darwin_rune_t = __darwin_wchar_t;
pub type __darwin_wint_t = ::std::os::raw::c_int;
pub type __darwin_clock_t = ::std::os::raw::c_ulong;
pub type __darwin_socklen_t = __uint32_t;
pub type __darwin_ssize_t = ::std::os::raw::c_long;
pub type __darwin_time_t = ::std::os::raw::c_long;
pub type __darwin_blkcnt_t = __int64_t;
pub type __darwin_blksize_t = __int32_t;
pub type __darwin_dev_t = __int32_t;
pub type __darwin_fsblkcnt_t = ::std::os::raw::c_uint;
pub type __darwin_fsfilcnt_t = ::std::os::raw::c_uint;
pub type __darwin_gid_t = __uint32_t;
pub type __darwin_id_t = __uint32_t;
pub type __darwin_ino64_t = __uint64_t;
pub type __darwin_ino_t = __darwin_ino64_t;
pub type __darwin_mach_port_name_t = __darwin_natural_t;
pub type __darwin_mach_port_t = __darwin_mach_port_name_t;
pub type __darwin_mode_t = __uint16_t;
pub type __darwin_off_t = __int64_t;
pub type __darwin_pid_t = __int32_t;
pub type __darwin_sigset_t = __uint32_t;
pub type __darwin_suseconds_t = __int32_t;
pub type __darwin_uid_t = __uint32_t;
pub type __darwin_useconds_t = __uint32_t;
pub type __darwin_uuid_t = [::std::os::raw::c_uchar; 16usize];
pub type __darwin_uuid_string_t = [::std::os::raw::c_char; 37usize];
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __darwin_pthread_handler_rec {
    pub __routine: ::std::option::Option<unsafe extern "C" fn(arg1: *mut ::std::os::raw::c_void)>,
    pub __arg: *mut ::std::os::raw::c_void,
    pub __next: *mut __darwin_pthread_handler_rec,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of __darwin_pthread_handler_rec"]
        [::std::mem::size_of::<__darwin_pthread_handler_rec>() - 24usize];
    ["Alignment of __darwin_pthread_handler_rec"]
        [::std::mem::align_of::<__darwin_pthread_handler_rec>() - 8usize];
    ["Offset of field: __darwin_pthread_handler_rec::__routine"]
        [::std::mem::offset_of!(__darwin_pthread_handler_rec, __routine) - 0usize];
    ["Offset of field: __darwin_pthread_handler_rec::__arg"]
        [::std::mem::offset_of!(__darwin_pthread_handler_rec, __arg) - 8usize];
    ["Offset of field: __darwin_pthread_handler_rec::__next"]
        [::std::mem::offset_of!(__darwin_pthread_handler_rec, __next) - 16usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _opaque_pthread_attr_t {
    pub __sig: ::std::os::raw::c_long,
    pub __opaque: [::std::os::raw::c_char; 56usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _opaque_pthread_attr_t"][::std::mem::size_of::<_opaque_pthread_attr_t>() - 64usize];
    ["Alignment of _opaque_pthread_attr_t"]
        [::std::mem::align_of::<_opaque_pthread_attr_t>() - 8usize];
    ["Offset of field: _opaque_pthread_attr_t::__sig"]
        [::std::mem::offset_of!(_opaque_pthread_attr_t, __sig) - 0usize];
    ["Offset of field: _opaque_pthread_attr_t::__opaque"]
        [::std::mem::offset_of!(_opaque_pthread_attr_t, __opaque) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _opaque_pthread_cond_t {
    pub __sig: ::std::os::raw::c_long,
    pub __opaque: [::std::os::raw::c_char; 40usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _opaque_pthread_cond_t"][::std::mem::size_of::<_opaque_pthread_cond_t>() - 48usize];
    ["Alignment of _opaque_pthread_cond_t"]
        [::std::mem::align_of::<_opaque_pthread_cond_t>() - 8usize];
    ["Offset of field: _opaque_pthread_cond_t::__sig"]
        [::std::mem::offset_of!(_opaque_pthread_cond_t, __sig) - 0usize];
    ["Offset of field: _opaque_pthread_cond_t::__opaque"]
        [::std::mem::offset_of!(_opaque_pthread_cond_t, __opaque) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _opaque_pthread_condattr_t {
    pub __sig: ::std::os::raw::c_long,
    pub __opaque: [::std::os::raw::c_char; 8usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _opaque_pthread_condattr_t"]
        [::std::mem::size_of::<_opaque_pthread_condattr_t>() - 16usize];
    ["Alignment of _opaque_pthread_condattr_t"]
        [::std::mem::align_of::<_opaque_pthread_condattr_t>() - 8usize];
    ["Offset of field: _opaque_pthread_condattr_t::__sig"]
        [::std::mem::offset_of!(_opaque_pthread_condattr_t, __sig) - 0usize];
    ["Offset of field: _opaque_pthread_condattr_t::__opaque"]
        [::std::mem::offset_of!(_opaque_pthread_condattr_t, __opaque) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _opaque_pthread_mutex_t {
    pub __sig: ::std::os::raw::c_long,
    pub __opaque: [::std::os::raw::c_char; 56usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _opaque_pthread_mutex_t"][::std::mem::size_of::<_opaque_pthread_mutex_t>() - 64usize];
    ["Alignment of _opaque_pthread_mutex_t"]
        [::std::mem::align_of::<_opaque_pthread_mutex_t>() - 8usize];
    ["Offset of field: _opaque_pthread_mutex_t::__sig"]
        [::std::mem::offset_of!(_opaque_pthread_mutex_t, __sig) - 0usize];
    ["Offset of field: _opaque_pthread_mutex_t::__opaque"]
        [::std::mem::offset_of!(_opaque_pthread_mutex_t, __opaque) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _opaque_pthread_mutexattr_t {
    pub __sig: ::std::os::raw::c_long,
    pub __opaque: [::std::os::raw::c_char; 8usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _opaque_pthread_mutexattr_t"]
        [::std::mem::size_of::<_opaque_pthread_mutexattr_t>() - 16usize];
    ["Alignment of _opaque_pthread_mutexattr_t"]
        [::std::mem::align_of::<_opaque_pthread_mutexattr_t>() - 8usize];
    ["Offset of field: _opaque_pthread_mutexattr_t::__sig"]
        [::std::mem::offset_of!(_opaque_pthread_mutexattr_t, __sig) - 0usize];
    ["Offset of field: _opaque_pthread_mutexattr_t::__opaque"]
        [::std::mem::offset_of!(_opaque_pthread_mutexattr_t, __opaque) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _opaque_pthread_once_t {
    pub __sig: ::std::os::raw::c_long,
    pub __opaque: [::std::os::raw::c_char; 8usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _opaque_pthread_once_t"][::std::mem::size_of::<_opaque_pthread_once_t>() - 16usize];
    ["Alignment of _opaque_pthread_once_t"]
        [::std::mem::align_of::<_opaque_pthread_once_t>() - 8usize];
    ["Offset of field: _opaque_pthread_once_t::__sig"]
        [::std::mem::offset_of!(_opaque_pthread_once_t, __sig) - 0usize];
    ["Offset of field: _opaque_pthread_once_t::__opaque"]
        [::std::mem::offset_of!(_opaque_pthread_once_t, __opaque) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _opaque_pthread_rwlock_t {
    pub __sig: ::std::os::raw::c_long,
    pub __opaque: [::std::os::raw::c_char; 192usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _opaque_pthread_rwlock_t"]
        [::std::mem::size_of::<_opaque_pthread_rwlock_t>() - 200usize];
    ["Alignment of _opaque_pthread_rwlock_t"]
        [::std::mem::align_of::<_opaque_pthread_rwlock_t>() - 8usize];
    ["Offset of field: _opaque_pthread_rwlock_t::__sig"]
        [::std::mem::offset_of!(_opaque_pthread_rwlock_t, __sig) - 0usize];
    ["Offset of field: _opaque_pthread_rwlock_t::__opaque"]
        [::std::mem::offset_of!(_opaque_pthread_rwlock_t, __opaque) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _opaque_pthread_rwlockattr_t {
    pub __sig: ::std::os::raw::c_long,
    pub __opaque: [::std::os::raw::c_char; 16usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _opaque_pthread_rwlockattr_t"]
        [::std::mem::size_of::<_opaque_pthread_rwlockattr_t>() - 24usize];
    ["Alignment of _opaque_pthread_rwlockattr_t"]
        [::std::mem::align_of::<_opaque_pthread_rwlockattr_t>() - 8usize];
    ["Offset of field: _opaque_pthread_rwlockattr_t::__sig"]
        [::std::mem::offset_of!(_opaque_pthread_rwlockattr_t, __sig) - 0usize];
    ["Offset of field: _opaque_pthread_rwlockattr_t::__opaque"]
        [::std::mem::offset_of!(_opaque_pthread_rwlockattr_t, __opaque) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _opaque_pthread_t {
    pub __sig: ::std::os::raw::c_long,
    pub __cleanup_stack: *mut __darwin_pthread_handler_rec,
    pub __opaque: [::std::os::raw::c_char; 8176usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _opaque_pthread_t"][::std::mem::size_of::<_opaque_pthread_t>() - 8192usize];
    ["Alignment of _opaque_pthread_t"][::std::mem::align_of::<_opaque_pthread_t>() - 8usize];
    ["Offset of field: _opaque_pthread_t::__sig"]
        [::std::mem::offset_of!(_opaque_pthread_t, __sig) - 0usize];
    ["Offset of field: _opaque_pthread_t::__cleanup_stack"]
        [::std::mem::offset_of!(_opaque_pthread_t, __cleanup_stack) - 8usize];
    ["Offset of field: _opaque_pthread_t::__opaque"]
        [::std::mem::offset_of!(_opaque_pthread_t, __opaque) - 16usize];
};
pub type __darwin_pthread_attr_t = _opaque_pthread_attr_t;
pub type __darwin_pthread_cond_t = _opaque_pthread_cond_t;
pub type __darwin_pthread_condattr_t = _opaque_pthread_condattr_t;
pub type __darwin_pthread_key_t = ::std::os::raw::c_ulong;
pub type __darwin_pthread_mutex_t = _opaque_pthread_mutex_t;
pub type __darwin_pthread_mutexattr_t = _opaque_pthread_mutexattr_t;
pub type __darwin_pthread_once_t = _opaque_pthread_once_t;
pub type __darwin_pthread_rwlock_t = _opaque_pthread_rwlock_t;
pub type __darwin_pthread_rwlockattr_t = _opaque_pthread_rwlockattr_t;
pub type __darwin_pthread_t = *mut _opaque_pthread_t;
pub type intmax_t = ::std::os::raw::c_long;
pub type uintmax_t = ::std::os::raw::c_ulong;
pub type i32_ = i32;
pub type u64_ = u64;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FScreenPlane {
    pub lower_left: [f64; 3usize],
    pub lower_right: [f64; 3usize],
    pub upper_right: [f64; 3usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of FScreenPlane"][::std::mem::size_of::<FScreenPlane>() - 72usize];
    ["Alignment of FScreenPlane"][::std::mem::align_of::<FScreenPlane>() - 8usize];
    ["Offset of field: FScreenPlane::lower_left"]
        [::std::mem::offset_of!(FScreenPlane, lower_left) - 0usize];
    ["Offset of field: FScreenPlane::lower_right"]
        [::std::mem::offset_of!(FScreenPlane, lower_right) - 24usize];
    ["Offset of field: FScreenPlane::upper_right"]
        [::std::mem::offset_of!(FScreenPlane, upper_right) - 48usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct short4 {
    pub x: i16,
    pub y: i16,
    pub z: i16,
    pub w: i16,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of short4"][::std::mem::size_of::<short4>() - 8usize];
    ["Alignment of short4"][::std::mem::align_of::<short4>() - 2usize];
    ["Offset of field: short4::x"][::std::mem::offset_of!(short4, x) - 0usize];
    ["Offset of field: short4::y"][::std::mem::offset_of!(short4, y) - 2usize];
    ["Offset of field: short4::z"][::std::mem::offset_of!(short4, z) - 4usize];
    ["Offset of field: short4::w"][::std::mem::offset_of!(short4, w) - 6usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ushort2 {
    pub x: u16,
    pub y: u16,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of ushort2"][::std::mem::size_of::<ushort2>() - 4usize];
    ["Alignment of ushort2"][::std::mem::align_of::<ushort2>() - 2usize];
    ["Offset of field: ushort2::x"][::std::mem::offset_of!(ushort2, x) - 0usize];
    ["Offset of field: ushort2::y"][::std::mem::offset_of!(ushort2, y) - 2usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ushort3 {
    pub x: u16,
    pub y: u16,
    pub z: u16,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of ushort3"][::std::mem::size_of::<ushort3>() - 6usize];
    ["Alignment of ushort3"][::std::mem::align_of::<ushort3>() - 2usize];
    ["Offset of field: ushort3::x"][::std::mem::offset_of!(ushort3, x) - 0usize];
    ["Offset of field: ushort3::y"][::std::mem::offset_of!(ushort3, y) - 2usize];
    ["Offset of field: ushort3::z"][::std::mem::offset_of!(ushort3, z) - 4usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct uint3 {
    pub x: u32,
    pub y: u32,
    pub z: u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of uint3"][::std::mem::size_of::<uint3>() - 12usize];
    ["Alignment of uint3"][::std::mem::align_of::<uint3>() - 4usize];
    ["Offset of field: uint3::x"][::std::mem::offset_of!(uint3, x) - 0usize];
    ["Offset of field: uint3::y"][::std::mem::offset_of!(uint3, y) - 4usize];
    ["Offset of field: uint3::z"][::std::mem::offset_of!(uint3, z) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct float2 {
    pub x: f32,
    pub y: f32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of float2"][::std::mem::size_of::<float2>() - 8usize];
    ["Alignment of float2"][::std::mem::align_of::<float2>() - 4usize];
    ["Offset of field: float2::x"][::std::mem::offset_of!(float2, x) - 0usize];
    ["Offset of field: float2::y"][::std::mem::offset_of!(float2, y) - 4usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct float3 {
    pub x: f32,
    pub y: f32,
    pub z: f32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of float3"][::std::mem::size_of::<float3>() - 12usize];
    ["Alignment of float3"][::std::mem::align_of::<float3>() - 4usize];
    ["Offset of field: float3::x"][::std::mem::offset_of!(float3, x) - 0usize];
    ["Offset of field: float3::y"][::std::mem::offset_of!(float3, y) - 4usize];
    ["Offset of field: float3::z"][::std::mem::offset_of!(float3, z) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct float4 {
    pub x: f32,
    pub y: f32,
    pub z: f32,
    pub w: f32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of float4"][::std::mem::size_of::<float4>() - 16usize];
    ["Alignment of float4"][::std::mem::align_of::<float4>() - 4usize];
    ["Offset of field: float4::x"][::std::mem::offset_of!(float4, x) - 0usize];
    ["Offset of field: float4::y"][::std::mem::offset_of!(float4, y) - 4usize];
    ["Offset of field: float4::z"][::std::mem::offset_of!(float4, z) - 8usize];
    ["Offset of field: float4::w"][::std::mem::offset_of!(float4, w) - 12usize];
};
#[doc = " Column major format"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mat4 {
    pub a: float4,
    pub b: float4,
    pub c: float4,
    pub d: float4,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of mat4"][::std::mem::size_of::<mat4>() - 64usize];
    ["Alignment of mat4"][::std::mem::align_of::<mat4>() - 4usize];
    ["Offset of field: mat4::a"][::std::mem::offset_of!(mat4, a) - 0usize];
    ["Offset of field: mat4::b"][::std::mem::offset_of!(mat4, b) - 16usize];
    ["Offset of field: mat4::c"][::std::mem::offset_of!(mat4, c) - 32usize];
    ["Offset of field: mat4::d"][::std::mem::offset_of!(mat4, d) - 48usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct aabb {
    pub minimum: float3,
    pub maximum: float3,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of aabb"][::std::mem::size_of::<aabb>() - 24usize];
    ["Alignment of aabb"][::std::mem::align_of::<aabb>() - 4usize];
    ["Offset of field: aabb::minimum"][::std::mem::offset_of!(aabb, minimum) - 0usize];
    ["Offset of field: aabb::maximum"][::std::mem::offset_of!(aabb, maximum) - 12usize];
};
#[doc = " Unpacked vertex information"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FVertexPNU {
    pub position: float3,
    pub normal: float3,
    pub uv: float2,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of FVertexPNU"][::std::mem::size_of::<FVertexPNU>() - 32usize];
    ["Alignment of FVertexPNU"][::std::mem::align_of::<FVertexPNU>() - 4usize];
    ["Offset of field: FVertexPNU::position"]
        [::std::mem::offset_of!(FVertexPNU, position) - 0usize];
    ["Offset of field: FVertexPNU::normal"][::std::mem::offset_of!(FVertexPNU, normal) - 12usize];
    ["Offset of field: FVertexPNU::uv"][::std::mem::offset_of!(FVertexPNU, uv) - 24usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FPackedVertex {
    pub position: float3,
    pub surface: short4,
    pub texture: ushort2,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of FPackedVertex"][::std::mem::size_of::<FPackedVertex>() - 24usize];
    ["Alignment of FPackedVertex"][::std::mem::align_of::<FPackedVertex>() - 4usize];
    ["Offset of field: FPackedVertex::position"]
        [::std::mem::offset_of!(FPackedVertex, position) - 0usize];
    ["Offset of field: FPackedVertex::surface"]
        [::std::mem::offset_of!(FPackedVertex, surface) - 12usize];
    ["Offset of field: FPackedVertex::texture"]
        [::std::mem::offset_of!(FPackedVertex, texture) - 20usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FColor {
    pub r: f32,
    pub g: f32,
    pub b: f32,
    pub a: f32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of FColor"][::std::mem::size_of::<FColor>() - 16usize];
    ["Alignment of FColor"][::std::mem::align_of::<FColor>() - 4usize];
    ["Offset of field: FColor::r"][::std::mem::offset_of!(FColor, r) - 0usize];
    ["Offset of field: FColor::g"][::std::mem::offset_of!(FColor, g) - 4usize];
    ["Offset of field: FColor::b"][::std::mem::offset_of!(FColor, b) - 8usize];
    ["Offset of field: FColor::a"][::std::mem::offset_of!(FColor, a) - 12usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FConfig {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FSession {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FBlob {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FMesh {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FMaterial {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FBlobRef {
    pub id: *mut FBlob,
    pub start: u64_,
    pub length: u64_,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of FBlobRef"][::std::mem::size_of::<FBlobRef>() - 24usize];
    ["Alignment of FBlobRef"][::std::mem::align_of::<FBlobRef>() - 8usize];
    ["Offset of field: FBlobRef::id"][::std::mem::offset_of!(FBlobRef, id) - 0usize];
    ["Offset of field: FBlobRef::start"][::std::mem::offset_of!(FBlobRef, start) - 8usize];
    ["Offset of field: FBlobRef::length"][::std::mem::offset_of!(FBlobRef, length) - 16usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FImage {
    _unused: [u8; 0],
}
pub const FPixelType_PIXEL_UBYTE: FPixelType = 0;
pub const FPixelType_PIXEL_FLOAT32: FPixelType = 1;
#[doc = " The type of pixels in an image"]
pub type FPixelType = ::std::os::raw::c_uint;
pub const FColorSpace_CS_LINEAR: FColorSpace = 0;
pub const FColorSpace_CS_SRGB: FColorSpace = 1;
#[doc = " The color space of an image"]
pub type FColorSpace = ::std::os::raw::c_uint;
#[doc = " A description of an image, for raw byte annotation."]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FImageRawDesc {
    pub width: u32,
    pub height: u32,
    pub n_channels: u8,
    pub byte_size: u64,
    pub type_: FPixelType,
    pub colorspace: FColorSpace,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of FImageRawDesc"][::std::mem::size_of::<FImageRawDesc>() - 32usize];
    ["Alignment of FImageRawDesc"][::std::mem::align_of::<FImageRawDesc>() - 8usize];
    ["Offset of field: FImageRawDesc::width"]
        [::std::mem::offset_of!(FImageRawDesc, width) - 0usize];
    ["Offset of field: FImageRawDesc::height"]
        [::std::mem::offset_of!(FImageRawDesc, height) - 4usize];
    ["Offset of field: FImageRawDesc::n_channels"]
        [::std::mem::offset_of!(FImageRawDesc, n_channels) - 8usize];
    ["Offset of field: FImageRawDesc::byte_size"]
        [::std::mem::offset_of!(FImageRawDesc, byte_size) - 16usize];
    ["Offset of field: FImageRawDesc::type_"]
        [::std::mem::offset_of!(FImageRawDesc, type_) - 24usize];
    ["Offset of field: FImageRawDesc::colorspace"]
        [::std::mem::offset_of!(FImageRawDesc, colorspace) - 28usize];
};
pub const FImageFileKind_IMG_UNKNOWN: FImageFileKind = 0;
pub const FImageFileKind_IMG_EXR: FImageFileKind = 1;
pub const FImageFileKind_IMG_HDR: FImageFileKind = 2;
pub const FImageFileKind_IMG_PNG: FImageFileKind = 3;
pub const FImageFileKind_IMG_JPEG: FImageFileKind = 4;
#[doc = " Lightweight file probe to choose decoding path"]
pub type FImageFileKind = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FImageFileInfo {
    pub kind: FImageFileKind,
    pub colorspace: FColorSpace,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of FImageFileInfo"][::std::mem::size_of::<FImageFileInfo>() - 8usize];
    ["Alignment of FImageFileInfo"][::std::mem::align_of::<FImageFileInfo>() - 4usize];
    ["Offset of field: FImageFileInfo::kind"]
        [::std::mem::offset_of!(FImageFileInfo, kind) - 0usize];
    ["Offset of field: FImageFileInfo::colorspace"]
        [::std::mem::offset_of!(FImageFileInfo, colorspace) - 4usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FTexture {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FTextureConfig {
    _unused: [u8; 0],
}
pub const FTextureFormat_FMT_R8: FTextureFormat = 0;
pub const FTextureFormat_FMT_RG8: FTextureFormat = 1;
pub const FTextureFormat_FMT_RGB8: FTextureFormat = 2;
pub const FTextureFormat_FMT_RGBA8: FTextureFormat = 3;
pub const FTextureFormat_FMT_SRGB8: FTextureFormat = 4;
pub const FTextureFormat_FMT_SRGB8_A8: FTextureFormat = 5;
pub const FTextureFormat_FMT_R16F: FTextureFormat = 6;
pub const FTextureFormat_FMT_RG16F: FTextureFormat = 7;
pub const FTextureFormat_FMT_RGB16F: FTextureFormat = 8;
pub const FTextureFormat_FMT_RGBA16F: FTextureFormat = 9;
pub const FTextureFormat_FMT_RGB32F: FTextureFormat = 10;
pub const FTextureFormat_FMT_RGBA32F: FTextureFormat = 11;
pub const FTextureFormat_FMT_R11F_G11F_B10F: FTextureFormat = 12;
pub const FTextureFormat_FMT_AUTO_SRGB_COLOR: FTextureFormat = 13;
pub const FTextureFormat_FMT_AUTO_LINEAR_DATA: FTextureFormat = 14;
#[doc = " The format of a texture"]
pub type FTextureFormat = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FEnvironmentLight {
    _unused: [u8; 0],
}
pub const FMeshIndexType_U16: FMeshIndexType = 0;
pub const FMeshIndexType_U32: FMeshIndexType = 1;
pub type FMeshIndexType = ::std::os::raw::c_uint;
pub const FMatOption_DOUBLE_SIDED: FMatOption = 0;
pub const FMatOption_UNLIT: FMatOption = 1;
pub const FMatOption_CLEARCOAT: FMatOption = 2;
pub const FMatOption_TRANSMISSION: FMatOption = 3;
pub const FMatOption_IOR: FMatOption = 4;
pub type FMatOption = ::std::os::raw::c_uint;
pub const FMatTexSemantic_BASE_COLOR_TEX: FMatTexSemantic = 0;
pub const FMatTexSemantic_NORMAL_TEX: FMatTexSemantic = 1;
pub const FMatTexSemantic_OCCLUSION_TEX: FMatTexSemantic = 2;
pub const FMatTexSemantic_EMISSIVE_TEX: FMatTexSemantic = 3;
pub const FMatTexSemantic_METAL_ROUGH_TEX: FMatTexSemantic = 4;
pub const FMatTexSemantic_CLEARCOAT_TEX: FMatTexSemantic = 5;
pub const FMatTexSemantic_CLEARCOAT_ROUGH_TEX: FMatTexSemantic = 6;
pub const FMatTexSemantic_CLEARCOAT_NORMAL_TEX: FMatTexSemantic = 7;
pub type FMatTexSemantic = ::std::os::raw::c_uint;
pub const FMatTexUVSlot_UV0: FMatTexUVSlot = 0;
pub const FMatTexUVSlot_UV1: FMatTexUVSlot = 1;
pub type FMatTexUVSlot = ::std::os::raw::c_uint;
pub const FMatBlendType_OPAQUE: FMatBlendType = 0;
pub const FMatBlendType_MASK: FMatBlendType = 1;
pub const FMatBlendType_BLEND: FMatBlendType = 2;
pub type FMatBlendType = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FMaterialConfig {
    _unused: [u8; 0],
}
pub const FMinFilter_MIN_FILTER_NEAREST: FMinFilter = 0;
pub const FMinFilter_MIN_FILTER_LINEAR: FMinFilter = 1;
pub const FMinFilter_MIN_FILTER_LINEAR_MIPMAP_LINEAR: FMinFilter = 2;
pub type FMinFilter = ::std::os::raw::c_uint;
pub const FMagFilter_MAG_FILTER_NEAREST: FMagFilter = 0;
pub const FMagFilter_MAG_FILTER_LINEAR: FMagFilter = 1;
pub type FMagFilter = ::std::os::raw::c_uint;
pub const FWrapMode_WRAP_CLAMP: FWrapMode = 0;
pub const FWrapMode_WRAP_REPEAT: FWrapMode = 1;
pub const FWrapMode_WRAP_MIRROR_REPEAT: FWrapMode = 2;
pub type FWrapMode = ::std::os::raw::c_uint;
pub const FTexAxis_AXIS_U: FTexAxis = 0;
pub const FTexAxis_AXIS_V: FTexAxis = 1;
pub const FTexAxis_AXIS_W: FTexAxis = 2;
pub type FTexAxis = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Sampler {
    pub pack: u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of Sampler"][::std::mem::size_of::<Sampler>() - 4usize];
    ["Alignment of Sampler"][::std::mem::align_of::<Sampler>() - 4usize];
    ["Offset of field: Sampler::pack"][::std::mem::offset_of!(Sampler, pack) - 0usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FLightConfig {
    _unused: [u8; 0],
}
pub const FLightType_POINT: FLightType = 0;
pub const FLightType_SPOT: FLightType = 1;
pub const FLightType_DIRECTIONAL: FLightType = 2;
pub const FLightType_SUN: FLightType = 3;
pub type FLightType = ::std::os::raw::c_uint;
pub const FRenderer_R_METAL: FRenderer = 0;
pub const FRenderer_R_OPENGL: FRenderer = 1;
pub const FRenderer_R_VULKAN: FRenderer = 2;
pub type FRenderer = ::std::os::raw::c_uint;
pub const FEye_EYE_LEFT: FEye = 0;
pub const FEye_EYE_RIGHT: FEye = 1;
#[doc = " Eye selection for stereo rendering"]
pub type FEye = ::std::os::raw::c_uint;
pub type __builtin_va_list = *mut ::std::os::raw::c_char;
pub struct BackfillDylib {
    __library: ::libloading::Library,
    pub mat4_identity: Result<unsafe extern "C" fn(arg1: *mut mat4), ::libloading::Error>,
    pub mat4_translate:
        Result<unsafe extern "C" fn(arg1: *mut mat4, arg2: float3), ::libloading::Error>,
    pub mat4_from_array:
        Result<unsafe extern "C" fn(out: *mut mat4, m: *const f32), ::libloading::Error>,
    pub pack_vertex_u16: Result<
        unsafe extern "C" fn(
            source: *const FVertexPNU,
            vertex_count: u32,
            index: *const ushort3,
            index_count: u32,
            dest: *mut FPackedVertex,
        ),
        ::libloading::Error,
    >,
    pub pack_vertex_u32: Result<
        unsafe extern "C" fn(
            source: *const FVertexPNU,
            vertex_count: u32,
            index: *const uint3,
            index_count: u32,
            dest: *mut FPackedVertex,
        ),
        ::libloading::Error,
    >,
    pub fblob_init_copy: Result<
        unsafe extern "C" fn(data: *const ::std::os::raw::c_char, byte_count: u64_) -> *mut FBlob,
        ::libloading::Error,
    >,
    pub fblob_acquire: Result<unsafe extern "C" fn(arg1: *mut FBlob), ::libloading::Error>,
    pub fblob_release: Result<unsafe extern "C" fn(arg1: *mut FBlob), ::libloading::Error>,
    pub fblobref_whole:
        Result<unsafe extern "C" fn(arg1: *mut FBlob) -> FBlobRef, ::libloading::Error>,
    pub fimg_init_decode_file:
        Result<unsafe extern "C" fn(arg1: FBlobRef) -> *mut FImage, ::libloading::Error>,
    pub fimg_init_raw: Result<
        unsafe extern "C" fn(arg1: FBlobRef, arg2: *const FImageRawDesc) -> *mut FImage,
        ::libloading::Error,
    >,
    pub fimg_probe: Result<
        unsafe extern "C" fn(arg1: FBlobRef, out: *mut FImageFileInfo) -> u8,
        ::libloading::Error,
    >,
    pub fimg_acquire: Result<unsafe extern "C" fn(arg1: *mut FImage), ::libloading::Error>,
    pub fimg_release: Result<unsafe extern "C" fn(arg1: *mut FImage), ::libloading::Error>,
    pub ftex_config_init: Result<
        unsafe extern "C" fn(arg1: *mut FImage, arg2: FTextureFormat) -> *mut FTextureConfig,
        ::libloading::Error,
    >,
    pub ftex_config_destroy:
        Result<unsafe extern "C" fn(arg1: *mut FTextureConfig), ::libloading::Error>,
    pub ftex_init: Result<
        unsafe extern "C" fn(arg1: *mut FSession, arg2: *mut FTextureConfig) -> *mut FTexture,
        ::libloading::Error,
    >,
    pub ftex_acquire: Result<unsafe extern "C" fn(arg1: *mut FTexture), ::libloading::Error>,
    pub ftex_release: Result<unsafe extern "C" fn(arg1: *mut FTexture), ::libloading::Error>,
    pub fenv_light_init_equirect: Result<
        unsafe extern "C" fn(arg1: *mut FSession, arg2: *mut FTexture) -> *mut FEnvironmentLight,
        ::libloading::Error,
    >,
    pub fenv_light_acquire:
        Result<unsafe extern "C" fn(arg1: *mut FEnvironmentLight), ::libloading::Error>,
    pub fenv_light_release:
        Result<unsafe extern "C" fn(arg1: *mut FEnvironmentLight), ::libloading::Error>,
    pub fenv_set_intensity: Result<
        unsafe extern "C" fn(arg1: *mut FEnvironmentLight, intensity: f32),
        ::libloading::Error,
    >,
    pub fmesh_init: Result<
        unsafe extern "C" fn(
            arg1: *mut FSession,
            vertex_reference: FBlobRef,
            vertex_count: u32,
            index_reference: FBlobRef,
            index_count: u32,
            arg2: FMeshIndexType,
            bounding_box: aabb,
        ) -> *mut FMesh,
        ::libloading::Error,
    >,
    pub fmesh_acquire: Result<unsafe extern "C" fn(arg1: *mut FMesh), ::libloading::Error>,
    pub fmesh_release: Result<unsafe extern "C" fn(arg1: *mut FMesh), ::libloading::Error>,
    pub fsamp_init: Result<unsafe extern "C" fn(arg1: *mut Sampler), ::libloading::Error>,
    pub fsamp_set_mag:
        Result<unsafe extern "C" fn(arg1: *mut Sampler, arg2: FMagFilter), ::libloading::Error>,
    pub fsamp_set_min:
        Result<unsafe extern "C" fn(arg1: *mut Sampler, arg2: FMinFilter), ::libloading::Error>,
    pub fsamp_set_wrap: Result<
        unsafe extern "C" fn(arg1: *mut Sampler, arg2: FWrapMode, arg3: FTexAxis),
        ::libloading::Error,
    >,
    pub fsamp_set_aniso:
        Result<unsafe extern "C" fn(arg1: *mut Sampler, arg2: u8), ::libloading::Error>,
    pub fmaterialconfig_init:
        Result<unsafe extern "C" fn() -> *mut FMaterialConfig, ::libloading::Error>,
    pub fmaterialconfig_destroy:
        Result<unsafe extern "C" fn(arg1: *mut FMaterialConfig), ::libloading::Error>,
    pub fmc_set_option: Result<
        unsafe extern "C" fn(arg1: *mut FMaterialConfig, arg2: FMatOption, arg3: u8),
        ::libloading::Error,
    >,
    pub fmc_set_texture: Result<
        unsafe extern "C" fn(
            arg1: *mut FMaterialConfig,
            arg2: FMatTexSemantic,
            arg3: FMatTexUVSlot,
            arg4: *mut FTexture,
            arg5: *mut Sampler,
        ),
        ::libloading::Error,
    >,
    pub fmc_enable_texture: Result<
        unsafe extern "C" fn(
            arg1: *mut FMaterialConfig,
            arg2: FMatTexSemantic,
            arg3: FMatTexUVSlot,
        ),
        ::libloading::Error,
    >,
    pub fmc_set_blend: Result<
        unsafe extern "C" fn(arg1: *mut FMaterialConfig, arg2: FMatBlendType),
        ::libloading::Error,
    >,
    pub fmaterial_init: Result<
        unsafe extern "C" fn(arg1: *mut FSession, arg2: *mut FMaterialConfig) -> *mut FMaterial,
        ::libloading::Error,
    >,
    pub fmaterial_acquire: Result<unsafe extern "C" fn(arg1: *mut FMaterial), ::libloading::Error>,
    pub fmaterial_release: Result<unsafe extern "C" fn(arg1: *mut FMaterial), ::libloading::Error>,
    pub fmaterial_set_base_color:
        Result<unsafe extern "C" fn(arg1: *mut FMaterial, arg2: FColor), ::libloading::Error>,
    pub fmaterial_set_roughness_metallic:
        Result<unsafe extern "C" fn(arg1: *mut FMaterial, r: f32, m: f32), ::libloading::Error>,
    pub fmaterial_set_ao_factor:
        Result<unsafe extern "C" fn(arg1: *mut FMaterial, ao: f32), ::libloading::Error>,
    pub fmaterial_set_emissive: Result<
        unsafe extern "C" fn(arg1: *mut FMaterial, strength: f32, factor: float3),
        ::libloading::Error,
    >,
    pub fmaterial_set_transmission:
        Result<unsafe extern "C" fn(arg1: *mut FMaterial, tf: f32), ::libloading::Error>,
    pub fmaterial_set_ior:
        Result<unsafe extern "C" fn(arg1: *mut FMaterial, ior: f32), ::libloading::Error>,
    pub fmaterial_set_clearcoat:
        Result<unsafe extern "C" fn(arg1: *mut FMaterial, cc: f32), ::libloading::Error>,
    pub fmaterial_set_texture: Result<
        unsafe extern "C" fn(
            arg1: *mut FMaterial,
            arg2: FMatTexSemantic,
            arg3: *mut FTexture,
            arg4: *mut Sampler,
        ),
        ::libloading::Error,
    >,
    pub flightconfig_init:
        Result<unsafe extern "C" fn(arg1: FLightType) -> *mut FLightConfig, ::libloading::Error>,
    pub flightconfig_destroy:
        Result<unsafe extern "C" fn(arg1: *mut FLightConfig), ::libloading::Error>,
    pub flc_set_intensity:
        Result<unsafe extern "C" fn(arg1: *mut FLightConfig, arg2: f32), ::libloading::Error>,
    pub flc_set_color:
        Result<unsafe extern "C" fn(arg1: *mut FLightConfig, arg2: FColor), ::libloading::Error>,
    pub flc_set_falloff:
        Result<unsafe extern "C" fn(arg1: *mut FLightConfig, arg2: f32), ::libloading::Error>,
    pub flc_set_direction:
        Result<unsafe extern "C" fn(arg1: *mut FLightConfig, arg2: float3), ::libloading::Error>,
    pub flc_set_spot_cone: Result<
        unsafe extern "C" fn(arg1: *mut FLightConfig, inner: f32, outer: f32),
        ::libloading::Error,
    >,
    pub flc_set_shadows:
        Result<unsafe extern "C" fn(arg1: *mut FLightConfig, arg2: u8), ::libloading::Error>,
    pub fconfig_init: Result<unsafe extern "C" fn() -> *mut FConfig, ::libloading::Error>,
    pub fconfig_destroy: Result<unsafe extern "C" fn(arg1: *mut FConfig), ::libloading::Error>,
    pub fconfig_set_title: Result<
        unsafe extern "C" fn(arg1: *mut FConfig, arg2: *const ::std::os::raw::c_char),
        ::libloading::Error,
    >,
    pub fconfig_set_display: Result<
        unsafe extern "C" fn(arg1: *mut FConfig, arg2: *const ::std::os::raw::c_char),
        ::libloading::Error,
    >,
    pub fconfig_set_device: Result<
        unsafe extern "C" fn(arg1: *mut FConfig, index: ::std::os::raw::c_int),
        ::libloading::Error,
    >,
    pub fconfig_set_screen: Result<
        unsafe extern "C" fn(
            arg1: *mut FConfig,
            w: ::std::os::raw::c_int,
            h: ::std::os::raw::c_int,
        ),
        ::libloading::Error,
    >,
    pub fconfig_set_log_debug:
        Result<unsafe extern "C" fn(arg1: *mut FConfig, arg2: u8), ::libloading::Error>,
    pub fconfig_set_fullscreen:
        Result<unsafe extern "C" fn(arg1: *mut FConfig, arg2: u8), ::libloading::Error>,
    pub fconfig_set_thread_count:
        Result<unsafe extern "C" fn(arg1: *mut FConfig, arg2: u8), ::libloading::Error>,
    pub fconfig_set_offaxis_plane: Result<
        unsafe extern "C" fn(arg1: *mut FConfig, arg2: *const FScreenPlane),
        ::libloading::Error,
    >,
    pub fconfig_set_renderer:
        Result<unsafe extern "C" fn(arg1: *mut FConfig, renderer: FRenderer), ::libloading::Error>,
    pub fconfig_set_stereo_eye:
        Result<unsafe extern "C" fn(arg1: *mut FConfig, arg2: FEye), ::libloading::Error>,
    pub fconfig_set_ssao:
        Result<unsafe extern "C" fn(arg1: *mut FConfig, arg2: u8), ::libloading::Error>,
    pub fs_init:
        Result<unsafe extern "C" fn(arg1: *mut FConfig) -> *mut FSession, ::libloading::Error>,
    pub fs_destroy: Result<unsafe extern "C" fn(arg1: *mut FSession), ::libloading::Error>,
    pub fs_set_postprocess:
        Result<unsafe extern "C" fn(arg1: *mut FSession, arg2: u8), ::libloading::Error>,
    pub fs_set_skybox_color:
        Result<unsafe extern "C" fn(arg1: *mut FSession, arg2: FColor), ::libloading::Error>,
    pub fs_set_environment_light: Result<
        unsafe extern "C" fn(arg1: *mut FSession, arg2: *mut FEnvironmentLight),
        ::libloading::Error,
    >,
    pub fs_update_head: Result<
        unsafe extern "C" fn(arg1: *mut FSession, pos: float3, quat: float4),
        ::libloading::Error,
    >,
    pub fs_frame: Result<unsafe extern "C" fn(arg1: *mut FSession) -> u8, ::libloading::Error>,
    pub fs_new_entity:
        Result<unsafe extern "C" fn(arg1: *mut FSession) -> i32_, ::libloading::Error>,
    pub fs_destroy_entity:
        Result<unsafe extern "C" fn(arg1: *mut FSession, entity: i32_), ::libloading::Error>,
    pub fs_add_renderable: Result<
        unsafe extern "C" fn(
            arg1: *mut FSession,
            entity: i32_,
            arg2: *mut FMesh,
            arg3: *mut FMaterial,
        ),
        ::libloading::Error,
    >,
    pub fs_del_renderable:
        Result<unsafe extern "C" fn(arg1: *mut FSession, entity: i32_), ::libloading::Error>,
    pub fs_set_transform: Result<
        unsafe extern "C" fn(arg1: *mut FSession, entity: i32_, arg2: *const mat4),
        ::libloading::Error,
    >,
    pub fs_set_parent: Result<
        unsafe extern "C" fn(arg1: *mut FSession, child: i32_, parent: i32_),
        ::libloading::Error,
    >,
    pub fs_debug_camera: Result<
        unsafe extern "C" fn(arg1: *mut FSession, out_model: *mut mat4, out_proj: *mut mat4),
        ::libloading::Error,
    >,
    pub fs_debug_camera_obj: Result<
        unsafe extern "C" fn(arg1: *mut FSession, file: *const ::std::os::raw::c_char),
        ::libloading::Error,
    >,
    pub fs_add_light: Result<
        unsafe extern "C" fn(arg1: *mut FSession, entity: i32_, arg2: *mut FLightConfig),
        ::libloading::Error,
    >,
    pub fs_del_light:
        Result<unsafe extern "C" fn(arg1: *mut FSession, entity: i32_), ::libloading::Error>,
    pub fs_set_visible: Result<
        unsafe extern "C" fn(arg1: *mut FSession, entity: i32_, arg2: u8),
        ::libloading::Error,
    >,
}
impl BackfillDylib {
    pub unsafe fn new<P>(path: P) -> Result<Self, ::libloading::Error>
    where
        P: AsRef<::std::ffi::OsStr>,
    {
        let library = ::libloading::Library::new(path.as_ref())?;
        Self::from_library(library)
    }
    pub unsafe fn from_library<L>(library: L) -> Result<Self, ::libloading::Error>
    where
        L: Into<::libloading::Library>,
    {
        let __library = library.into();
        let mat4_identity = __library.get(b"mat4_identity\0").map(|sym| *sym);
        let mat4_translate = __library.get(b"mat4_translate\0").map(|sym| *sym);
        let mat4_from_array = __library.get(b"mat4_from_array\0").map(|sym| *sym);
        let pack_vertex_u16 = __library.get(b"pack_vertex_u16\0").map(|sym| *sym);
        let pack_vertex_u32 = __library.get(b"pack_vertex_u32\0").map(|sym| *sym);
        let fblob_init_copy = __library.get(b"fblob_init_copy\0").map(|sym| *sym);
        let fblob_acquire = __library.get(b"fblob_acquire\0").map(|sym| *sym);
        let fblob_release = __library.get(b"fblob_release\0").map(|sym| *sym);
        let fblobref_whole = __library.get(b"fblobref_whole\0").map(|sym| *sym);
        let fimg_init_decode_file = __library.get(b"fimg_init_decode_file\0").map(|sym| *sym);
        let fimg_init_raw = __library.get(b"fimg_init_raw\0").map(|sym| *sym);
        let fimg_probe = __library.get(b"fimg_probe\0").map(|sym| *sym);
        let fimg_acquire = __library.get(b"fimg_acquire\0").map(|sym| *sym);
        let fimg_release = __library.get(b"fimg_release\0").map(|sym| *sym);
        let ftex_config_init = __library.get(b"ftex_config_init\0").map(|sym| *sym);
        let ftex_config_destroy = __library.get(b"ftex_config_destroy\0").map(|sym| *sym);
        let ftex_init = __library.get(b"ftex_init\0").map(|sym| *sym);
        let ftex_acquire = __library.get(b"ftex_acquire\0").map(|sym| *sym);
        let ftex_release = __library.get(b"ftex_release\0").map(|sym| *sym);
        let fenv_light_init_equirect = __library.get(b"fenv_light_init_equirect\0").map(|sym| *sym);
        let fenv_light_acquire = __library.get(b"fenv_light_acquire\0").map(|sym| *sym);
        let fenv_light_release = __library.get(b"fenv_light_release\0").map(|sym| *sym);
        let fenv_set_intensity = __library.get(b"fenv_set_intensity\0").map(|sym| *sym);
        let fmesh_init = __library.get(b"fmesh_init\0").map(|sym| *sym);
        let fmesh_acquire = __library.get(b"fmesh_acquire\0").map(|sym| *sym);
        let fmesh_release = __library.get(b"fmesh_release\0").map(|sym| *sym);
        let fsamp_init = __library.get(b"fsamp_init\0").map(|sym| *sym);
        let fsamp_set_mag = __library.get(b"fsamp_set_mag\0").map(|sym| *sym);
        let fsamp_set_min = __library.get(b"fsamp_set_min\0").map(|sym| *sym);
        let fsamp_set_wrap = __library.get(b"fsamp_set_wrap\0").map(|sym| *sym);
        let fsamp_set_aniso = __library.get(b"fsamp_set_aniso\0").map(|sym| *sym);
        let fmaterialconfig_init = __library.get(b"fmaterialconfig_init\0").map(|sym| *sym);
        let fmaterialconfig_destroy = __library.get(b"fmaterialconfig_destroy\0").map(|sym| *sym);
        let fmc_set_option = __library.get(b"fmc_set_option\0").map(|sym| *sym);
        let fmc_set_texture = __library.get(b"fmc_set_texture\0").map(|sym| *sym);
        let fmc_enable_texture = __library.get(b"fmc_enable_texture\0").map(|sym| *sym);
        let fmc_set_blend = __library.get(b"fmc_set_blend\0").map(|sym| *sym);
        let fmaterial_init = __library.get(b"fmaterial_init\0").map(|sym| *sym);
        let fmaterial_acquire = __library.get(b"fmaterial_acquire\0").map(|sym| *sym);
        let fmaterial_release = __library.get(b"fmaterial_release\0").map(|sym| *sym);
        let fmaterial_set_base_color = __library.get(b"fmaterial_set_base_color\0").map(|sym| *sym);
        let fmaterial_set_roughness_metallic = __library
            .get(b"fmaterial_set_roughness_metallic\0")
            .map(|sym| *sym);
        let fmaterial_set_ao_factor = __library.get(b"fmaterial_set_ao_factor\0").map(|sym| *sym);
        let fmaterial_set_emissive = __library.get(b"fmaterial_set_emissive\0").map(|sym| *sym);
        let fmaterial_set_transmission = __library
            .get(b"fmaterial_set_transmission\0")
            .map(|sym| *sym);
        let fmaterial_set_ior = __library.get(b"fmaterial_set_ior\0").map(|sym| *sym);
        let fmaterial_set_clearcoat = __library.get(b"fmaterial_set_clearcoat\0").map(|sym| *sym);
        let fmaterial_set_texture = __library.get(b"fmaterial_set_texture\0").map(|sym| *sym);
        let flightconfig_init = __library.get(b"flightconfig_init\0").map(|sym| *sym);
        let flightconfig_destroy = __library.get(b"flightconfig_destroy\0").map(|sym| *sym);
        let flc_set_intensity = __library.get(b"flc_set_intensity\0").map(|sym| *sym);
        let flc_set_color = __library.get(b"flc_set_color\0").map(|sym| *sym);
        let flc_set_falloff = __library.get(b"flc_set_falloff\0").map(|sym| *sym);
        let flc_set_direction = __library.get(b"flc_set_direction\0").map(|sym| *sym);
        let flc_set_spot_cone = __library.get(b"flc_set_spot_cone\0").map(|sym| *sym);
        let flc_set_shadows = __library.get(b"flc_set_shadows\0").map(|sym| *sym);
        let fconfig_init = __library.get(b"fconfig_init\0").map(|sym| *sym);
        let fconfig_destroy = __library.get(b"fconfig_destroy\0").map(|sym| *sym);
        let fconfig_set_title = __library.get(b"fconfig_set_title\0").map(|sym| *sym);
        let fconfig_set_display = __library.get(b"fconfig_set_display\0").map(|sym| *sym);
        let fconfig_set_device = __library.get(b"fconfig_set_device\0").map(|sym| *sym);
        let fconfig_set_screen = __library.get(b"fconfig_set_screen\0").map(|sym| *sym);
        let fconfig_set_log_debug = __library.get(b"fconfig_set_log_debug\0").map(|sym| *sym);
        let fconfig_set_fullscreen = __library.get(b"fconfig_set_fullscreen\0").map(|sym| *sym);
        let fconfig_set_thread_count = __library.get(b"fconfig_set_thread_count\0").map(|sym| *sym);
        let fconfig_set_offaxis_plane = __library
            .get(b"fconfig_set_offaxis_plane\0")
            .map(|sym| *sym);
        let fconfig_set_renderer = __library.get(b"fconfig_set_renderer\0").map(|sym| *sym);
        let fconfig_set_stereo_eye = __library.get(b"fconfig_set_stereo_eye\0").map(|sym| *sym);
        let fconfig_set_ssao = __library.get(b"fconfig_set_ssao\0").map(|sym| *sym);
        let fs_init = __library.get(b"fs_init\0").map(|sym| *sym);
        let fs_destroy = __library.get(b"fs_destroy\0").map(|sym| *sym);
        let fs_set_postprocess = __library.get(b"fs_set_postprocess\0").map(|sym| *sym);
        let fs_set_skybox_color = __library.get(b"fs_set_skybox_color\0").map(|sym| *sym);
        let fs_set_environment_light = __library.get(b"fs_set_environment_light\0").map(|sym| *sym);
        let fs_update_head = __library.get(b"fs_update_head\0").map(|sym| *sym);
        let fs_frame = __library.get(b"fs_frame\0").map(|sym| *sym);
        let fs_new_entity = __library.get(b"fs_new_entity\0").map(|sym| *sym);
        let fs_destroy_entity = __library.get(b"fs_destroy_entity\0").map(|sym| *sym);
        let fs_add_renderable = __library.get(b"fs_add_renderable\0").map(|sym| *sym);
        let fs_del_renderable = __library.get(b"fs_del_renderable\0").map(|sym| *sym);
        let fs_set_transform = __library.get(b"fs_set_transform\0").map(|sym| *sym);
        let fs_set_parent = __library.get(b"fs_set_parent\0").map(|sym| *sym);
        let fs_debug_camera = __library.get(b"fs_debug_camera\0").map(|sym| *sym);
        let fs_debug_camera_obj = __library.get(b"fs_debug_camera_obj\0").map(|sym| *sym);
        let fs_add_light = __library.get(b"fs_add_light\0").map(|sym| *sym);
        let fs_del_light = __library.get(b"fs_del_light\0").map(|sym| *sym);
        let fs_set_visible = __library.get(b"fs_set_visible\0").map(|sym| *sym);
        Ok(BackfillDylib {
            __library,
            mat4_identity,
            mat4_translate,
            mat4_from_array,
            pack_vertex_u16,
            pack_vertex_u32,
            fblob_init_copy,
            fblob_acquire,
            fblob_release,
            fblobref_whole,
            fimg_init_decode_file,
            fimg_init_raw,
            fimg_probe,
            fimg_acquire,
            fimg_release,
            ftex_config_init,
            ftex_config_destroy,
            ftex_init,
            ftex_acquire,
            ftex_release,
            fenv_light_init_equirect,
            fenv_light_acquire,
            fenv_light_release,
            fenv_set_intensity,
            fmesh_init,
            fmesh_acquire,
            fmesh_release,
            fsamp_init,
            fsamp_set_mag,
            fsamp_set_min,
            fsamp_set_wrap,
            fsamp_set_aniso,
            fmaterialconfig_init,
            fmaterialconfig_destroy,
            fmc_set_option,
            fmc_set_texture,
            fmc_enable_texture,
            fmc_set_blend,
            fmaterial_init,
            fmaterial_acquire,
            fmaterial_release,
            fmaterial_set_base_color,
            fmaterial_set_roughness_metallic,
            fmaterial_set_ao_factor,
            fmaterial_set_emissive,
            fmaterial_set_transmission,
            fmaterial_set_ior,
            fmaterial_set_clearcoat,
            fmaterial_set_texture,
            flightconfig_init,
            flightconfig_destroy,
            flc_set_intensity,
            flc_set_color,
            flc_set_falloff,
            flc_set_direction,
            flc_set_spot_cone,
            flc_set_shadows,
            fconfig_init,
            fconfig_destroy,
            fconfig_set_title,
            fconfig_set_display,
            fconfig_set_device,
            fconfig_set_screen,
            fconfig_set_log_debug,
            fconfig_set_fullscreen,
            fconfig_set_thread_count,
            fconfig_set_offaxis_plane,
            fconfig_set_renderer,
            fconfig_set_stereo_eye,
            fconfig_set_ssao,
            fs_init,
            fs_destroy,
            fs_set_postprocess,
            fs_set_skybox_color,
            fs_set_environment_light,
            fs_update_head,
            fs_frame,
            fs_new_entity,
            fs_destroy_entity,
            fs_add_renderable,
            fs_del_renderable,
            fs_set_transform,
            fs_set_parent,
            fs_debug_camera,
            fs_debug_camera_obj,
            fs_add_light,
            fs_del_light,
            fs_set_visible,
        })
    }
    #[doc = " Initialize a matrix to the indentity."]
    pub unsafe fn mat4_identity(&self, arg1: *mut mat4) {
        (self
            .mat4_identity
            .as_ref()
            .expect("Expected function, got error."))(arg1)
    }
    #[doc = " Append a translation to the given matrix."]
    pub unsafe fn mat4_translate(&self, arg1: *mut mat4, arg2: float3) {
        (self
            .mat4_translate
            .as_ref()
            .expect("Expected function, got error."))(arg1, arg2)
    }
    #[doc = " Overwrite a matrix with the context of the column-major array."]
    pub unsafe fn mat4_from_array(&self, out: *mut mat4, m: *const f32) {
        (self
            .mat4_from_array
            .as_ref()
            .expect("Expected function, got error."))(out, m)
    }
    pub unsafe fn pack_vertex_u16(
        &self,
        source: *const FVertexPNU,
        vertex_count: u32,
        index: *const ushort3,
        index_count: u32,
        dest: *mut FPackedVertex,
    ) {
        (self
            .pack_vertex_u16
            .as_ref()
            .expect("Expected function, got error."))(
            source,
            vertex_count,
            index,
            index_count,
            dest,
        )
    }
    pub unsafe fn pack_vertex_u32(
        &self,
        source: *const FVertexPNU,
        vertex_count: u32,
        index: *const uint3,
        index_count: u32,
        dest: *mut FPackedVertex,
    ) {
        (self
            .pack_vertex_u32
            .as_ref()
            .expect("Expected function, got error."))(
            source,
            vertex_count,
            index,
            index_count,
            dest,
        )
    }
    pub unsafe fn fblob_init_copy(
        &self,
        data: *const ::std::os::raw::c_char,
        byte_count: u64_,
    ) -> *mut FBlob {
        (self
            .fblob_init_copy
            .as_ref()
            .expect("Expected function, got error."))(data, byte_count)
    }
    pub unsafe fn fblob_acquire(&self, arg1: *mut FBlob) {
        (self
            .fblob_acquire
            .as_ref()
            .expect("Expected function, got error."))(arg1)
    }
    pub unsafe fn fblob_release(&self, arg1: *mut FBlob) {
        (self
            .fblob_release
            .as_ref()
            .expect("Expected function, got error."))(arg1)
    }
    pub unsafe fn fblobref_whole(&self, arg1: *mut FBlob) -> FBlobRef {
        (self
            .fblobref_whole
            .as_ref()
            .expect("Expected function, got error."))(arg1)
    }
    #[doc = " Decode a blob of bytes as an image file"]
    pub unsafe fn fimg_init_decode_file(&self, arg1: FBlobRef) -> *mut FImage {
        (self
            .fimg_init_decode_file
            .as_ref()
            .expect("Expected function, got error."))(arg1)
    }
    #[doc = " Initialize an image from raw pixel memory referenced by the blob.\n The blob region must contain exactly width*height*channels*bytes_per_pixel\n bytes."]
    pub unsafe fn fimg_init_raw(&self, arg1: FBlobRef, arg2: *const FImageRawDesc) -> *mut FImage {
        (self
            .fimg_init_raw
            .as_ref()
            .expect("Expected function, got error."))(arg1, arg2)
    }
    #[doc = " Inspect magic bytes to classify file kind. Returns 1 if recognized."]
    pub unsafe fn fimg_probe(&self, arg1: FBlobRef, out: *mut FImageFileInfo) -> u8 {
        (self
            .fimg_probe
            .as_ref()
            .expect("Expected function, got error."))(arg1, out)
    }
    pub unsafe fn fimg_acquire(&self, arg1: *mut FImage) {
        (self
            .fimg_acquire
            .as_ref()
            .expect("Expected function, got error."))(arg1)
    }
    pub unsafe fn fimg_release(&self, arg1: *mut FImage) {
        (self
            .fimg_release
            .as_ref()
            .expect("Expected function, got error."))(arg1)
    }
    pub unsafe fn ftex_config_init(
        &self,
        arg1: *mut FImage,
        arg2: FTextureFormat,
    ) -> *mut FTextureConfig {
        (self
            .ftex_config_init
            .as_ref()
            .expect("Expected function, got error."))(arg1, arg2)
    }
    pub unsafe fn ftex_config_destroy(&self, arg1: *mut FTextureConfig) {
        (self
            .ftex_config_destroy
            .as_ref()
            .expect("Expected function, got error."))(arg1)
    }
    pub unsafe fn ftex_init(
        &self,
        arg1: *mut FSession,
        arg2: *mut FTextureConfig,
    ) -> *mut FTexture {
        (self
            .ftex_init
            .as_ref()
            .expect("Expected function, got error."))(arg1, arg2)
    }
    pub unsafe fn ftex_acquire(&self, arg1: *mut FTexture) {
        (self
            .ftex_acquire
            .as_ref()
            .expect("Expected function, got error."))(arg1)
    }
    pub unsafe fn ftex_release(&self, arg1: *mut FTexture) {
        (self
            .ftex_release
            .as_ref()
            .expect("Expected function, got error."))(arg1)
    }
    pub unsafe fn fenv_light_init_equirect(
        &self,
        arg1: *mut FSession,
        arg2: *mut FTexture,
    ) -> *mut FEnvironmentLight {
        (self
            .fenv_light_init_equirect
            .as_ref()
            .expect("Expected function, got error."))(arg1, arg2)
    }
    pub unsafe fn fenv_light_acquire(&self, arg1: *mut FEnvironmentLight) {
        (self
            .fenv_light_acquire
            .as_ref()
            .expect("Expected function, got error."))(arg1)
    }
    pub unsafe fn fenv_light_release(&self, arg1: *mut FEnvironmentLight) {
        (self
            .fenv_light_release
            .as_ref()
            .expect("Expected function, got error."))(arg1)
    }
    pub unsafe fn fenv_set_intensity(&self, arg1: *mut FEnvironmentLight, intensity: f32) {
        (self
            .fenv_set_intensity
            .as_ref()
            .expect("Expected function, got error."))(arg1, intensity)
    }
    pub unsafe fn fmesh_init(
        &self,
        arg1: *mut FSession,
        vertex_reference: FBlobRef,
        vertex_count: u32,
        index_reference: FBlobRef,
        index_count: u32,
        arg2: FMeshIndexType,
        bounding_box: aabb,
    ) -> *mut FMesh {
        (self
            .fmesh_init
            .as_ref()
            .expect("Expected function, got error."))(
            arg1,
            vertex_reference,
            vertex_count,
            index_reference,
            index_count,
            arg2,
            bounding_box,
        )
    }
    pub unsafe fn fmesh_acquire(&self, arg1: *mut FMesh) {
        (self
            .fmesh_acquire
            .as_ref()
            .expect("Expected function, got error."))(arg1)
    }
    pub unsafe fn fmesh_release(&self, arg1: *mut FMesh) {
        (self
            .fmesh_release
            .as_ref()
            .expect("Expected function, got error."))(arg1)
    }
    pub unsafe fn fsamp_init(&self, arg1: *mut Sampler) {
        (self
            .fsamp_init
            .as_ref()
            .expect("Expected function, got error."))(arg1)
    }
    pub unsafe fn fsamp_set_mag(&self, arg1: *mut Sampler, arg2: FMagFilter) {
        (self
            .fsamp_set_mag
            .as_ref()
            .expect("Expected function, got error."))(arg1, arg2)
    }
    pub unsafe fn fsamp_set_min(&self, arg1: *mut Sampler, arg2: FMinFilter) {
        (self
            .fsamp_set_min
            .as_ref()
            .expect("Expected function, got error."))(arg1, arg2)
    }
    pub unsafe fn fsamp_set_wrap(&self, arg1: *mut Sampler, arg2: FWrapMode, arg3: FTexAxis) {
        (self
            .fsamp_set_wrap
            .as_ref()
            .expect("Expected function, got error."))(arg1, arg2, arg3)
    }
    pub unsafe fn fsamp_set_aniso(&self, arg1: *mut Sampler, arg2: u8) {
        (self
            .fsamp_set_aniso
            .as_ref()
            .expect("Expected function, got error."))(arg1, arg2)
    }
    #[doc = " Create a material configuration. Material configs are used to specialize\n material capabilities"]
    pub unsafe fn fmaterialconfig_init(&self) -> *mut FMaterialConfig {
        (self
            .fmaterialconfig_init
            .as_ref()
            .expect("Expected function, got error."))()
    }
    pub unsafe fn fmaterialconfig_destroy(&self, arg1: *mut FMaterialConfig) {
        (self
            .fmaterialconfig_destroy
            .as_ref()
            .expect("Expected function, got error."))(arg1)
    }
    #[doc = " Set an option on a material.\n NOTE: Attempting to set options parameters (like transmission) on a material\n that is not enabled in the config will result in an error"]
    pub unsafe fn fmc_set_option(&self, arg1: *mut FMaterialConfig, arg2: FMatOption, arg3: u8) {
        (self
            .fmc_set_option
            .as_ref()
            .expect("Expected function, got error."))(arg1, arg2, arg3)
    }
    #[doc = " Set, and enable, the use of a texture for a given semantic.\n NOTE: Attempting to set a texture for a semantic on a constructed material\n that does not have that semantic enabled is a hard error."]
    pub unsafe fn fmc_set_texture(
        &self,
        arg1: *mut FMaterialConfig,
        arg2: FMatTexSemantic,
        arg3: FMatTexUVSlot,
        arg4: *mut FTexture,
        arg5: *mut Sampler,
    ) {
        (self
            .fmc_set_texture
            .as_ref()
            .expect("Expected function, got error."))(arg1, arg2, arg3, arg4, arg5)
    }
    #[doc = " Enable, but do not set, the use of a texture semantic."]
    pub unsafe fn fmc_enable_texture(
        &self,
        arg1: *mut FMaterialConfig,
        arg2: FMatTexSemantic,
        arg3: FMatTexUVSlot,
    ) {
        (self
            .fmc_enable_texture
            .as_ref()
            .expect("Expected function, got error."))(arg1, arg2, arg3)
    }
    pub unsafe fn fmc_set_blend(&self, arg1: *mut FMaterialConfig, arg2: FMatBlendType) {
        (self
            .fmc_set_blend
            .as_ref()
            .expect("Expected function, got error."))(arg1, arg2)
    }
    pub unsafe fn fmaterial_init(
        &self,
        arg1: *mut FSession,
        arg2: *mut FMaterialConfig,
    ) -> *mut FMaterial {
        (self
            .fmaterial_init
            .as_ref()
            .expect("Expected function, got error."))(arg1, arg2)
    }
    pub unsafe fn fmaterial_acquire(&self, arg1: *mut FMaterial) {
        (self
            .fmaterial_acquire
            .as_ref()
            .expect("Expected function, got error."))(arg1)
    }
    pub unsafe fn fmaterial_release(&self, arg1: *mut FMaterial) {
        (self
            .fmaterial_release
            .as_ref()
            .expect("Expected function, got error."))(arg1)
    }
    pub unsafe fn fmaterial_set_base_color(&self, arg1: *mut FMaterial, arg2: FColor) {
        (self
            .fmaterial_set_base_color
            .as_ref()
            .expect("Expected function, got error."))(arg1, arg2)
    }
    pub unsafe fn fmaterial_set_roughness_metallic(&self, arg1: *mut FMaterial, r: f32, m: f32) {
        (self
            .fmaterial_set_roughness_metallic
            .as_ref()
            .expect("Expected function, got error."))(arg1, r, m)
    }
    pub unsafe fn fmaterial_set_ao_factor(&self, arg1: *mut FMaterial, ao: f32) {
        (self
            .fmaterial_set_ao_factor
            .as_ref()
            .expect("Expected function, got error."))(arg1, ao)
    }
    pub unsafe fn fmaterial_set_emissive(
        &self,
        arg1: *mut FMaterial,
        strength: f32,
        factor: float3,
    ) {
        (self
            .fmaterial_set_emissive
            .as_ref()
            .expect("Expected function, got error."))(arg1, strength, factor)
    }
    pub unsafe fn fmaterial_set_transmission(&self, arg1: *mut FMaterial, tf: f32) {
        (self
            .fmaterial_set_transmission
            .as_ref()
            .expect("Expected function, got error."))(arg1, tf)
    }
    pub unsafe fn fmaterial_set_ior(&self, arg1: *mut FMaterial, ior: f32) {
        (self
            .fmaterial_set_ior
            .as_ref()
            .expect("Expected function, got error."))(arg1, ior)
    }
    pub unsafe fn fmaterial_set_clearcoat(&self, arg1: *mut FMaterial, cc: f32) {
        (self
            .fmaterial_set_clearcoat
            .as_ref()
            .expect("Expected function, got error."))(arg1, cc)
    }
    pub unsafe fn fmaterial_set_texture(
        &self,
        arg1: *mut FMaterial,
        arg2: FMatTexSemantic,
        arg3: *mut FTexture,
        arg4: *mut Sampler,
    ) {
        (self
            .fmaterial_set_texture
            .as_ref()
            .expect("Expected function, got error."))(arg1, arg2, arg3, arg4)
    }
    pub unsafe fn flightconfig_init(&self, arg1: FLightType) -> *mut FLightConfig {
        (self
            .flightconfig_init
            .as_ref()
            .expect("Expected function, got error."))(arg1)
    }
    pub unsafe fn flightconfig_destroy(&self, arg1: *mut FLightConfig) {
        (self
            .flightconfig_destroy
            .as_ref()
            .expect("Expected function, got error."))(arg1)
    }
    pub unsafe fn flc_set_intensity(&self, arg1: *mut FLightConfig, arg2: f32) {
        (self
            .flc_set_intensity
            .as_ref()
            .expect("Expected function, got error."))(arg1, arg2)
    }
    pub unsafe fn flc_set_color(&self, arg1: *mut FLightConfig, arg2: FColor) {
        (self
            .flc_set_color
            .as_ref()
            .expect("Expected function, got error."))(arg1, arg2)
    }
    pub unsafe fn flc_set_falloff(&self, arg1: *mut FLightConfig, arg2: f32) {
        (self
            .flc_set_falloff
            .as_ref()
            .expect("Expected function, got error."))(arg1, arg2)
    }
    pub unsafe fn flc_set_direction(&self, arg1: *mut FLightConfig, arg2: float3) {
        (self
            .flc_set_direction
            .as_ref()
            .expect("Expected function, got error."))(arg1, arg2)
    }
    pub unsafe fn flc_set_spot_cone(&self, arg1: *mut FLightConfig, inner: f32, outer: f32) {
        (self
            .flc_set_spot_cone
            .as_ref()
            .expect("Expected function, got error."))(arg1, inner, outer)
    }
    pub unsafe fn flc_set_shadows(&self, arg1: *mut FLightConfig, arg2: u8) {
        (self
            .flc_set_shadows
            .as_ref()
            .expect("Expected function, got error."))(arg1, arg2)
    }
    pub unsafe fn fconfig_init(&self) -> *mut FConfig {
        (self
            .fconfig_init
            .as_ref()
            .expect("Expected function, got error."))()
    }
    pub unsafe fn fconfig_destroy(&self, arg1: *mut FConfig) {
        (self
            .fconfig_destroy
            .as_ref()
            .expect("Expected function, got error."))(arg1)
    }
    pub unsafe fn fconfig_set_title(
        &self,
        arg1: *mut FConfig,
        arg2: *const ::std::os::raw::c_char,
    ) {
        (self
            .fconfig_set_title
            .as_ref()
            .expect("Expected function, got error."))(arg1, arg2)
    }
    pub unsafe fn fconfig_set_display(
        &self,
        arg1: *mut FConfig,
        arg2: *const ::std::os::raw::c_char,
    ) {
        (self
            .fconfig_set_display
            .as_ref()
            .expect("Expected function, got error."))(arg1, arg2)
    }
    pub unsafe fn fconfig_set_device(&self, arg1: *mut FConfig, index: ::std::os::raw::c_int) {
        (self
            .fconfig_set_device
            .as_ref()
            .expect("Expected function, got error."))(arg1, index)
    }
    pub unsafe fn fconfig_set_screen(
        &self,
        arg1: *mut FConfig,
        w: ::std::os::raw::c_int,
        h: ::std::os::raw::c_int,
    ) {
        (self
            .fconfig_set_screen
            .as_ref()
            .expect("Expected function, got error."))(arg1, w, h)
    }
    pub unsafe fn fconfig_set_log_debug(&self, arg1: *mut FConfig, arg2: u8) {
        (self
            .fconfig_set_log_debug
            .as_ref()
            .expect("Expected function, got error."))(arg1, arg2)
    }
    pub unsafe fn fconfig_set_fullscreen(&self, arg1: *mut FConfig, arg2: u8) {
        (self
            .fconfig_set_fullscreen
            .as_ref()
            .expect("Expected function, got error."))(arg1, arg2)
    }
    pub unsafe fn fconfig_set_thread_count(&self, arg1: *mut FConfig, arg2: u8) {
        (self
            .fconfig_set_thread_count
            .as_ref()
            .expect("Expected function, got error."))(arg1, arg2)
    }
    #[doc = " Enable off-axis mode using this screen plane."]
    pub unsafe fn fconfig_set_offaxis_plane(&self, arg1: *mut FConfig, arg2: *const FScreenPlane) {
        (self
            .fconfig_set_offaxis_plane
            .as_ref()
            .expect("Expected function, got error."))(arg1, arg2)
    }
    pub unsafe fn fconfig_set_renderer(&self, arg1: *mut FConfig, renderer: FRenderer) {
        (self
            .fconfig_set_renderer
            .as_ref()
            .expect("Expected function, got error."))(arg1, renderer)
    }
    #[doc = " Set off-axis eye"]
    pub unsafe fn fconfig_set_stereo_eye(&self, arg1: *mut FConfig, arg2: FEye) {
        (self
            .fconfig_set_stereo_eye
            .as_ref()
            .expect("Expected function, got error."))(arg1, arg2)
    }
    pub unsafe fn fconfig_set_ssao(&self, arg1: *mut FConfig, arg2: u8) {
        (self
            .fconfig_set_ssao
            .as_ref()
            .expect("Expected function, got error."))(arg1, arg2)
    }
    #[doc = " Create a new backfill session"]
    pub unsafe fn fs_init(&self, arg1: *mut FConfig) -> *mut FSession {
        (self
            .fs_init
            .as_ref()
            .expect("Expected function, got error."))(arg1)
    }
    pub unsafe fn fs_destroy(&self, arg1: *mut FSession) {
        (self
            .fs_destroy
            .as_ref()
            .expect("Expected function, got error."))(arg1)
    }
    pub unsafe fn fs_set_postprocess(&self, arg1: *mut FSession, arg2: u8) {
        (self
            .fs_set_postprocess
            .as_ref()
            .expect("Expected function, got error."))(arg1, arg2)
    }
    pub unsafe fn fs_set_skybox_color(&self, arg1: *mut FSession, arg2: FColor) {
        (self
            .fs_set_skybox_color
            .as_ref()
            .expect("Expected function, got error."))(arg1, arg2)
    }
    pub unsafe fn fs_set_environment_light(
        &self,
        arg1: *mut FSession,
        arg2: *mut FEnvironmentLight,
    ) {
        (self
            .fs_set_environment_light
            .as_ref()
            .expect("Expected function, got error."))(arg1, arg2)
    }
    pub unsafe fn fs_update_head(&self, arg1: *mut FSession, pos: float3, quat: float4) {
        (self
            .fs_update_head
            .as_ref()
            .expect("Expected function, got error."))(arg1, pos, quat)
    }
    #[doc = " Render a frame. Processes window events. Returns false if the window has\n been closed."]
    pub unsafe fn fs_frame(&self, arg1: *mut FSession) -> u8 {
        (self
            .fs_frame
            .as_ref()
            .expect("Expected function, got error."))(arg1)
    }
    #[doc = " Create a new, blank, entity"]
    pub unsafe fn fs_new_entity(&self, arg1: *mut FSession) -> i32_ {
        (self
            .fs_new_entity
            .as_ref()
            .expect("Expected function, got error."))(arg1)
    }
    pub unsafe fn fs_destroy_entity(&self, arg1: *mut FSession, entity: i32_) {
        (self
            .fs_destroy_entity
            .as_ref()
            .expect("Expected function, got error."))(arg1, entity)
    }
    #[doc = " Add a renderable component to an entity. You may delete the mesh and\n material after this call."]
    pub unsafe fn fs_add_renderable(
        &self,
        arg1: *mut FSession,
        entity: i32_,
        arg2: *mut FMesh,
        arg3: *mut FMaterial,
    ) {
        (self
            .fs_add_renderable
            .as_ref()
            .expect("Expected function, got error."))(arg1, entity, arg2, arg3)
    }
    pub unsafe fn fs_del_renderable(&self, arg1: *mut FSession, entity: i32_) {
        (self
            .fs_del_renderable
            .as_ref()
            .expect("Expected function, got error."))(arg1, entity)
    }
    #[doc = " Set the transform of an entity"]
    pub unsafe fn fs_set_transform(&self, arg1: *mut FSession, entity: i32_, arg2: *const mat4) {
        (self
            .fs_set_transform
            .as_ref()
            .expect("Expected function, got error."))(arg1, entity, arg2)
    }
    #[doc = " Sets the parent, and CLEARS/overwrites the childs current transform if there\n is one."]
    pub unsafe fn fs_set_parent(&self, arg1: *mut FSession, child: i32_, parent: i32_) {
        (self
            .fs_set_parent
            .as_ref()
            .expect("Expected function, got error."))(arg1, child, parent)
    }
    #[doc = " Extract current camera matrix info"]
    pub unsafe fn fs_debug_camera(
        &self,
        arg1: *mut FSession,
        out_model: *mut mat4,
        out_proj: *mut mat4,
    ) {
        (self
            .fs_debug_camera
            .as_ref()
            .expect("Expected function, got error."))(arg1, out_model, out_proj)
    }
    pub unsafe fn fs_debug_camera_obj(
        &self,
        arg1: *mut FSession,
        file: *const ::std::os::raw::c_char,
    ) {
        (self
            .fs_debug_camera_obj
            .as_ref()
            .expect("Expected function, got error."))(arg1, file)
    }
    #[doc = " Add a light component to an entity. You may destroy or reuse the\n configuration after this call."]
    pub unsafe fn fs_add_light(&self, arg1: *mut FSession, entity: i32_, arg2: *mut FLightConfig) {
        (self
            .fs_add_light
            .as_ref()
            .expect("Expected function, got error."))(arg1, entity, arg2)
    }
    pub unsafe fn fs_del_light(&self, arg1: *mut FSession, entity: i32_) {
        (self
            .fs_del_light
            .as_ref()
            .expect("Expected function, got error."))(arg1, entity)
    }
    pub unsafe fn fs_set_visible(&self, arg1: *mut FSession, entity: i32_, arg2: u8) {
        (self
            .fs_set_visible
            .as_ref()
            .expect("Expected function, got error."))(arg1, entity, arg2)
    }
}
